Chat_app/Chat_app/urls.py
from django.contrib import admin
from django.urls import path, include

# Media + static routes and urls import
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('rooms/', include('rooms.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   

Chat_app/core/urls.py
from django.urls import path
from .views import index, signup, update_profile, profile

# Build-in views import for login and logout 
from django.contrib.auth import views
from .forms import LoginForm

# Media + static routes and urls import
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('update_profile', update_profile, name='update_profile')
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Chat_app/rooms/urls.py
from django.urls import path
from .views import chatgroup, chat

# Media + static routes and urls import
from django.conf import settings
from django.conf.urls.static import static

app_name = 'rooms'

urlpatterns = [
    path('', chatgroup, name='chatgroup'),
    path('<slug:slug>/', chat, name='chat')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Chat_app/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Django's build-in signals for model operations
from django.db.models.signals import post_save
from django.dispatch import receiver

# Pillow image re-sizing import
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    birth_date = models.DateField(blank=True, null=True)
    picture = models.ImageField(default='profile_pics/default_pic.png', upload_to='profile_pics/', blank=True) 
    
    def __str__(self):
        return self.user.username
    
    # Re-sizing profile picture to 400 X 400 pixels if not already
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        pic = Image.open(self.picture.path)
        if pic.height > 400 or pic.width > 400:
            output_size = (400, 400)
            pic.thumbnail(output_size)
            pic.save(self.picture.path)
            
            
# Signals to create/save profile when User is created/updated
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

Chat_app/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth.models import User
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            "username": forms.TextInput(attrs={
                "placeholder": "Enter your Username",
                "class": "form-control"
            })
        }
    
    # The password fields are defined on the form class itself, not on the model.
    # So override them to set widget attributes  
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
            
        self.fields['password1'].widget = forms.PasswordInput(attrs={
            "placeholder": "Enter your Password",
            "class": "form-control"
        })
            
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            "placeholder": "Confirm Password",
            "class": "form-control"
        })
        
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        widgets = {
            "username": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "first_name": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "last_name": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control"
            })
        }
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birth_date', 'picture']
        widgets = {
            "birth_date": forms.DateInput(attrs={
            "class": "form-control",
            "type": "date"
            }),
            "picture": forms.FileInput(attrs={
            "class": "form-control"
            })
        }
      
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Enter your Username",
        "class": "form-control"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter your Password",
        "class": "form-control"
    }))
        

Chat_app/core/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db import transaction

from .forms import SignUpForm, UserUpdateForm, ProfileUpdateForm

# Homepage View
def index(request):
    return render(request, 'core/index.html')

# Sign Up View
def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            user.set_password(form.cleaned_data.get('password1'))
            user = authenticate(username=user.username, password=form.cleaned_data.get('password1'))
            user.save()
            
            login(request, user)
            return redirect('core:index')
    else:
        form = SignUpForm()
        
    return render(request, 'core/signup.html', {"form": form})


# Profile Update View
@login_required
@transaction.atomic         # Send signal to database whenever profile is update
def update_profile(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('core:profile')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    
    return render(request, 'core/update_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })
    
    
# Profile View   
@login_required
def profile(request):  
    return render(request, 'core/profile.html')

Chat_app/core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Chat_app</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <style>
      .navbar .nav-link {
        color: lightgoldenrodyellow;
        font-weight: 600;
      }
      .btn {
        font-weight: 700;
      }

      body {
        padding-top: 100px;
        padding-bottom: 50px;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand link-warning h1" href="{% url 'core:index' %}">Chat App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'rooms:chatgroup' %}">Rooms</a>
                </li>
                <li class="nav-item">
                  <form method="post" action="{% url 'core:logout' %}"> {% csrf_token %}
                    <button type="submit" class="nav-link btn">Log out</button>
                  </form>  
                </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    {% block scripts %}
    {% endblock %}
    
  </body>
</html>

Chat_app/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container" id="Intro-section">
      <div class="row justify-content-center">
        <div class="col border border-3 border-dark bg-light rounded text-center px-2 py-4" style="max-width:35rem;">
          {% if request.user.is_authenticated %}
            <h3>Welcome Back!!!</h3>
            <p>
              Hi there!👏 <strong>{{ request.user.username }}</strong> welcome back to Chat App. Catch up with your friends, colleagues, or communities click the link down below to start chatting again!
            </p>
            <div class="d-flex justify-content-center gap-2">
              <a href="{% url 'rooms:chatgroup' %}" class="btn btn-warning">Rooms</a>
            </div>
          {% else %}
            <h3>Welcome to Real-Time Conversations</h3>
            <p>
              Join multiple chat rooms and engage in real-time discussions. Connect with friends, colleagues, or communities in dedicated spaces. Start chatting now!
            </p>
          <div class="d-flex justify-content-center gap-2">
            <a href="{% url 'core:signup' %}" class="btn btn-warning">Sign up</a>
            <a href="{% url 'core:login' %}" class="btn btn-danger">Log in</a>
          <div>
          {% endif %}
        </div>
      </div>
    </div>
{% endblock %}
    

Chat_app/core/templates/core/login.html
{% extends 'core/base.html' %}
{% block content %}
    
    <div class="container" id="form-section">
        <div class="row justify-content-center">
            <div class="col bg-light border border-dark rounded p-3" style="max-width:25rem;">
                <div class="mb-3 pb-3">
                    <h2 class="mb-0">Log In</h2>
                    <small class="text-muted">Please enter your credentials to continue</small>
                </div>
                <form method="post" action=".">  {% csrf_token %}
                    <div class="my-3">
                        <label for="id_username" class="form-label">Username:</label>
                        {{ form.username }}
                    </div>
                    <div class="my-3">
                        <label for="id_password" class="form-label">Password:</label>
                        {{ form.password }}
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <div class="form-check small">
                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                            <label class="form-check-label" for="defaultCheck1">
                                Remember me
                            </label>
                        </div>
                        <a href="#" class="small text-info">Forgot Password?</a>
                    </div>
                    <button type="submit" class="btn btn-warning fw-bold my-2">Log In</button>
                        <div class="text-center small mt-2">
                            Don't have an account? <a href="{% url 'core:signup' %}" class="link-info">Sign up</a>
                          </div>

                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="form_errors alert alert-danger">
                                        <p>{{ error|escape }}</p>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Chat_app/core/templates/core/profile.html
{% extends "core/base.html" %}

{% block content %}
    <div class="container" id="profile-section">
        <div class="row border border-dark">
            <div class="col-12 border-bottom bg-dark text-warning py-2">
                <h3 class="mb-0">My Profile</h3>
            </div>
            <div class="col-md-4 d-flex justify-content-center align-items-center py-2">
                <img src="{{ user.profile.picture.url }}" alt="{{ user.username }}" class="img-thumbnail">
            </div>
            <div class="col-md-8 py-2">
                <h5 class="border-bottom pb-2">Personal Details</h5>
                <div class="row gy-2">
                    <div class="col-6">
                        <strong>Username</strong><br>
                        <p class="text-muted">{{ user.username }}</p>
                    </div>
                    <div class="col-6">
                        <strong>Name</strong><br>
                        {% if user.first_name and user.last_name %}
                            <p class="text-muted">{{ user.first_name }} {{ user.last_name }}</p>
                        {% endif %}
                    </div>
                    <div class="col-6">
                        <strong>E-mail</strong><br>
                        {% if user.email %}
                            <p class="text-muted">{{ user.email }}</p>
                        {% endif %}
                    </div>
                    <div class="col-6">
                        <strong>Birth Date</strong><br>
                        {% if user.profile.birth_date %}
                            <p class="text-muted">{{ user.profile.birth_date }}</p>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        {% if user == request.user %}
                            <a href="{% url 'core:update_profile' %}" class="btn btn-secondary">Edit Profile</a>
                        {% endif%}
                    </div>
                </div>
            </div>
        </div> 
    </div>

{% endblock%}

Chat_app/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col border border-dark rounded bg-light p-3" style="max-width:28rem;">
            <div class="mb-2 p-2">
                <h3>Chat app</h3>
                <div class="text-center my-2 p-2">
                    <h5 class="text-muted mb-0">Create an Account</h5>
                    <h4>Sign up to Chat App</h4>
                </div>
            </div>
            <form method="post" action=".">  {% csrf_token %}
                <div class="my-3">
                    <label class="form-label" for="id_username">Username:</label>
                    {{ form.username }}
                </div>
                <div class="my-3">        
                    <label class="form-label" for="id_password1">Password:</label>
                    {{ form.password1 }}
                </div>
                <div class="my-3">
                    <label class="form-label" for="id_password2">Confirm Password:</label>
                    {{ form.password2 }}
                </div>
                <div class="my-2 pt-2 border-top">
                    <button type="submit" class="btn btn-info my-2">Sign Up</button>
                </div>
                <small>Have an account? <a href="{% url 'core:login' %}" class="link-info">Sign in</a>

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="form_errors alert alert-danger my-2">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

Chat_app/core/templates/core/update_profile.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container" id="profileUpdateForm">
    <div class="row border border-2 bg-light rounded">
        <div class="col-12 py-2">
            <h3 class="py-2 border-bottom border-dark">Edit Profile</h3>
        </div>
        <div class="col py-2">
            <form action="{% url 'core:update_profile' %}" method="post" enctype="multipart/form-data">   {% csrf_token %}
                <div class="row gy-3">
                    <div class="col-6">
                        <label for="id_username" class="form-label">Username:</label>
                        {{ user_form.username }}
                    </div>
                    <div class="col-6">
                        <label for="id_email" class="form-label">Email:</label>
                        {{ user_form.email }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_first_name" class="form-label">First Name:</label>
                        {{ user_form.first_name }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_last_name" class="form-label">Last Name:</label>
                        {{ user_form.last_name }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_birth_date" class="form-label">Birth Date:</label>
                        {{ profile_form.birth_date }}
                    </div>
                    
                    <div class="col-12">
                        {% if request.user.profile.picture %}
                            <p>Current Profile Image:</p>
                                <img src="{{ request.user.profile.picture.url }}" alt="Profile Image" class="img-thumbnail" style="max-width: 150px;">
                        {% endif %}
                        <div class="my-3"> 
                            <div class="input-group mb-2"> 
                                <span class="input-group-text">Currently</span> 
                                <div class="form-control d-flex h-auto"> 
                                    <span class="text-break flex-grow-1"> 
                                        <a href="{{ profile_form.picture.value }}">{{profile_form.picture.value}}</a> 
                                    </span> 
                                    <span class="align-self-center ml-2"> 
                                        <span class="form-check"> 
                                            <input type="checkbox" name="picture-clear" id="picture-clear_id" class="form-check-input"> 
                                            <label class="form-check-label mb-0" for="picture-clear_id">Clear</label> 
                                        </span> 
                                    </span> 
                                </div>
                            </div>
                        </div>
                        <label for="id_picture" class="form-label">Profile Picture:</label>
                            {{ profile_form.picture }}

                        <div class="mt-4 text-center">
                            <button type="submit" class="btn btn-warning">Save</button>
                            <a href="{% url 'core:profile' %}" class="btn btn-danger ml-2">Cancel</a>
                        </div>    
                    </div>
                
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="form_errors alert alert-danger my-2">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}